### ISSUE TITLE
Rule groups are getting double escaped

### ISSUE THREAD

**Issue by justincmoy** [grafana/cortex-tools#132]
https://github.com/grafana/cortex-tools/pull/131 shows an example where `GetRuleGroup` would escape the space in `escaped namespace` and `buildRequest` would re-escape it, resulting in the failed test result of `%2520` from `%20`.

**Comment by jtlisi** [comment]
@justincmoy Are you running into an issue with double escaping? Are you already setting your rule groups and rule namespaces to be escaped in the file?

**Comment by justincmoy** [comment]
Yes, it's an issue with double escaping. We are not escaping the rule groups or namespaces in the file. I think this is only an issue with `GetRuleGroup` and `DeleteRuleGroup`: https://github.com/grafana/cortex-tools/blob/6fdb58208db8c96fb1e9b02c9debf605984165d3/pkg/client/rules.go#L47-L49

**Comment by justincmoy** [comment]
This is fixed in https://github.com/grafana/cortex-tools/pull/140.
