### ISSUE TITLE
cortex.Client: allow overriding/adding a roundtrip to the client

### ISSUE THREAD

**Issue by roidelapluie** [grafana/cortex-tools#144]
Hello,

I am developing a terraform provider for cortex (open source, apache 2). Terraform has a special transport https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/logging#NewTransport that helps a lot while debugging during provider development. It would be great to be able to inject that kind of transport inside the client.Client.

**Comment by jtlisi** [comment]
Makes sense. I will happily approve a PR that allows for the transport to be overrided. I generally like the approach taken in the [Thanos s3 client](https://github.com/thanos-io/thanos/blob/master/pkg/objstore/s3/s3.go) for this. However, feel free to do whatever you think makes the most sense.
