### ISSUE TITLE
Deprecate overrides-exporter command in favor of Cortex target

### ISSUE THREAD

**Issue by 56quarters** [grafana/cortex-tools#147]
Once there's a release of Cortex that includes the `overrides-exporter` target, the same functionality in this tool should be deprecated

https://github.com/cortexproject/cortex/pull/3785
https://github.com/cortexproject/cortex/issues/1433

**Comment by gouthamve** [comment]
We still need functionality to export "presets" and I've vendored the upstream cortex usage here: https://github.com/grafana/cortex-tools/pull/154

I don't think a Cortex "target" will work and presets is too specific to how we run things.
