### ISSUE TITLE
Cortextool `rules check` should incorporate `promtool check rules`

### ISSUE THREAD

**Issue by simonswine** [grafana/cortex-tools#148]
Currently `cortextool rules check` is only checking for the format of the recording rule name.

We should incorporate the duplicate checks from `promtool check rules`, as this currently can't be used easily because of the `namespace` field:

```
$ promtool check rules *.yml
Checking alerting/definitions/ci.yml
  FAILED:
my-rule.yml: yaml: unmarshal errors:
  line 1: field namespace not found in type rulefmt.RuleGroups 
```

### Workaround

```bash
for rule_file in *.yaml; do 
  promtool check rules <(cat "${rule_file}" |python -c 'import json, sys, yaml ; y=yaml.safe_load(sys.stdin.read()) ; del y["namespace"]; yaml.dump(y, sys.stdout)')
done
```

**Comment by genebean** [comment]
The workaround here does not account for drunning `promtool test rules <test file>.yml` as the test file is where the included rules files are defined.

**Comment by genebean** [comment]
Does #149 also fix the issue with `promtool test rules <test file>.yml`?
