### ISSUE TITLE
Unable To Load Alertmanager Config Given MacOS Big Sur Blocking /tmp/ Write Access

### ISSUE THREAD

**Issue by Carmezim** [grafana/cortex-tools#173]
MacOS Big Sur does not allow write access to the root dir.

During validation of the alertmanager configs cortextool tries to write to `/tmp/validate-configxxxxxx` which is blocked by MacOS and fails with `read-only file system`.

Example:
```
ERRO[0001] server returned HTTP status 400 Bad Request: error validating Alertmanager config: 
mkdir /tmp/validate-config003623358: read-only file system  
fields.msg="error validating Alertmanager config: mkdir /tmp/validate-config003623358: read-only file system" status="400 Bad Request"
```

Is there a way to provide or modify the validation directory?

**Comment by Carmezim** [comment]
That is a cortex issue actually

**Comment by vinitmasaun** [comment]
@Carmezim I am facing the same issue.  Could you provide details on how you resolved this issue?
