### ISSUE TITLE
Docker image - grafana/cortex-tools:v0.10.5 - linux/amd64

### ISSUE THREAD

**Issue by dsegurag** [grafana/cortex-tools#219]
Hi there!

I just realised that my GitLab pipelines have started to fail since `v0.10.5` Docker image version with the following error:

```console
Using docker image sha256:5c46890f7c19a54bffa956147a339b2c058c7c370144d83a7b92e16c7fb34359 for grafana/cortex-tools:v0.10.5 with digest grafana/cortex-tools@sha256:b3f36d4c02580f12ebdaa92460ca955b003ab9a815cb5f83891489fded656a35 ...
standard_init_linux.go:228: exec user process caused: exec format error
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

After checking the Docker Hub website (https://hub.docker.com/r/grafana/cortex-tools/tags) I noticed that there is no `amd64` image available for `v0.10.5` version.

![image](https://user-images.githubusercontent.com/21098646/140477589-774c13e1-6586-468a-a579-f41cd8ad55fe.png)

Could you please upload it?

Thanks in advance. 🙇🏼‍♂️

**Comment by stevesg** [comment]
Thanks! This should be fixed now. We pushed the image with the wrong architecture. It works on my laptop now:

```
$ arch
x86_64
$ docker run -it grafana/cortex-tools:v0.10.5 version
version 0.10.5
checking latest version... You are on the latest version
```
