### ISSUE TITLE
[analyse] grafana unmarshal errors

### ISSUE THREAD

**Issue by AkashSirimanna** [grafana/cortex-tools#241]
**Problem**

Running `analyse grafana` on version 0.10.7 of `cortextool` does not complete 100% successfully. The tool has difficulties trying to unmarshal panel json, most likely due to the tool not being compatible with Grafana 8.3.4.

The errors are along the lines of 
```
unmarshal board: json: cannot unmarshal object into Go struct field Board.panels of type []struct { Type string "json:\"type,omitempty\""; Params []string "json:\"params,omitempty\"" }
```

OR 

```
unmarshal board: json: cannot unmarshal number 4.8 into Go struct field Board.panels of type int ...
unmarshal board: json: cannot unmarshal object into Go struct field Board.panels of type string ...
```

Due to this, the `metricsUsed` list the analyse commands returns is incomplete.

**Comment by eamonryan** [comment]
Tagging @hjet per our discussion today - I'm seeing this issue also against Grafana 8.4.x

**Comment by hjet** [comment]
Related: https://github.com/grafana-tools/sdk/pull/190
And: https://github.com/grafana-tools/sdk/pull/201

Temporary workaround (uses https://github.com/grafana-tools/sdk/pull/190 branch of `sdk`):

```bash
git clone git@github.com:grafana/cortex-tools.git
git checkout temp-update-grafana-sdk
make cortextool
```

The binary will be at `cmd/cortextool/cortextool`. Move that to inside your path.

**Comment by gilreathjw** [comment]
This error appears to still be happening

**Comment by m4vr0x** [comment]
Indeed, still failing (using with Grafana v10.0.1 - 5a30620b85)
