### ISSUE TITLE
rules diff subcommand reports spurious changes

### ISSUE THREAD

**Issue by ekpdt** [grafana/cortex-tools#30]
Loading the follow namespace/file into cortex:
```
groups:
- name: my_group
  rules:
  - record: value
    expr: vector(0)
    labels:
      val: '0'
```
And then immediately diffing with `cortextool rules diff` will produce a report that the group `my_group` will be updated.
```
Changes are indicated with the following symbols:
  + updated

The following changes will be made if the provided rule set is synced:
~ Namespace: my_namespace
  ~ Group: my_group

Diff Summary: 0 Groups Created, 1 Groups Updated, 0 Groups Deleted
```

This is because the rules file is unmarshalled to a Prometheus `Rule` struct with `Annotations map[string]string = nil` while Cortex assigns the same field to an empty map. This leads [the deep equality check](https://github.com/grafana/cortextool/blob/master/pkg/rules/compare.go#L83) to report a difference.

Users can work around this bug by adding an empty annotations map to their rule files. But this is a little counterintuitive given that [documentation](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule) doesn't show `annotations` as a valid field for recording rules. It might be better for cortextool to fill this field in itself if it is going to rely on on `reflect.deepEquals`.

**Comment by tomwilkie** [comment]
Closed by #61
