### ISSUE TITLE
Add a flag to check whenever rules have colons (:) on their names

### ISSUE THREAD

**Issue by gotjosh** [grafana/cortex-tools#42]
Recording rules have [best practices](https://prometheus.io/docs/practices/rules/) to follow, one of them is the `level:metric:operations` naming convention. 

To ensure, rules are named in a proper way within a file I think we could add a flag to `rules lint` that ensures the metric name follows this.

**Comment by tomwilkie** [comment]
Have you seen promtool?  Does it not already do this? https://github.com/prometheus/prometheus/pull/2605

**Comment by gotjosh** [comment]
@tomwilkie I have and it does not. Check metrics only performs checks for ensuring a help text and validating the suffixes of metrics.

Earlier in the past week I even opened https://github.com/prometheus/prometheus/issues/7301 as I believe `promtool check rules` could do more. This [year's GSoC for Prometheus](https://summerofcode.withgoogle.com/projects/#5270684160229376) is aiming to build `promfmt` which I'm hoping is the thing we need to supersede the `cortextool rules lint` command.

**Comment by gotjosh** [comment]
Closed via https://github.com/grafana/cortex-tools/pull/46
