### ISSUE TITLE
go.mod and repo name discrepancy

### ISSUE THREAD

**Issue by sh0rez** [grafana/cortex-tools#59]
The `go.mod` file specifies `cortextool` as the name, while the repo is actually named `cortex-tools`.

While this is not a big problem, it is confusing when naively trying to import code from this repo:

```
go: github.com/sh0rez/gctl/pkg/spec imports
	github.com/grafana/cortex-tools/pkg/client: github.com/grafana/cortex-tools@v0.2.2: parsing go.mod:
	module declares its path as: github.com/grafana/cortextool
	        but was required as: github.com/grafana/cortex-tools
```

To not actually break go imports, the "clean" solution would probably be to rename this repo to `grafana/cortextool`

**Comment by jtlisi** [comment]
@sh0rez instead of reverting the name to `cortextool` I think it would make more sense to update all of the paths in the repo. I am not aware of anyone vendoring this code and it would be relatively trivial to update the path at this point.

**Comment by sh0rez** [comment]
That's fine as well. Just starting off with a project that vendors this one, so not a problem changing it there
