### ISSUE TITLE
Allow send TLS client certificate to Cortex API

### ISSUE THREAD

**Issue by vitovitolo** [grafana/cortex-tools#63]
👋 hi!

I'm running Cortex on k8s for a while and I've protected the API with client TLS authentication with the help of [ingress-nginx controller](https://kubernetes.github.io/ingress-nginx/).

Right now I want to use cortex-tools to lint and load rules in an automated fashion from a CI pipeline. Thus I would like to authenticate the http client with a TLS client certificate.

I saw you're using go http client so it shouldn't be hard to add tls certs to CortexClient struct:

https://github.com/grafana/cortex-tools/blob/94327d5fb0208cf8bd82f843755c018e39d763d7/pkg/client/client.go#L31

It would be something like https://gist.github.com/michaljemala/d6f4e01c4834bf47a9c4

The cli flags would look like:
```
cortextools rules load my-rule.yml --address=ADDRESS --id=ID --cacert ca.pem --key client.key --cert client.pem
```

and also adding environment variables:
```
CORTEX_TLS_CA_CERT
CORTEX_TLS_CLIENT_KEY
CORTEX_TLS_CLIENT_CERT
```

I'm wondering if you consider tls client auth useful for the project. In that case I'm willing to send a PR.

Thanks!

**Comment by tomwilkie** [comment]
This sounds like something we'd want! Yes please a PR would be very welcome.
