### ISSUE TITLE
New mixed-unit durations from prometheus/common v0.11.0 cannot be deserialized

### ISSUE THREAD

**Issue by jutley** [grafana/cortex-tools#83]
Recently, github.com/prometheus/common@v0.11.0 introduced the ability to define durations using mixed units, e.g. 1h30m. This change [is not backwards compatible](https://github.com/prometheus/common/issues/257), which creates issues for this project.

This change has been in the cortexproject/cortex master branch for a while, which some extremely notable users (Grafana Cloud!) are using. These changes are also in this project's master branch, but are unreleased. This means that there is no released version of cortextool that can properly interact with Prometheus rules stored in these Cortex instances.

All this requires is a new release of this project! Please cut a new release!

**Comment by gotjosh** [comment]
thank you for reporting this - will be releasing a new version shortly.

**Comment by gotjosh** [comment]
[A new version has been released](https://github.com/grafana/cortex-tools/releases/tag/v0.3.0), please let us know if any other issues come up.
